In [1]:
import numpy as np
import pandas as pd

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [5]:
np.arange(1, 10, 2, dtype = np.float64)

array([ 1.,  3.,  5.,  7.,  9.])

In [6]:
x = np.arange(1, 10)

In [7]:
ds = np.arange(1, 10, 2)
ds.ndim

1

In [8]:
ds

array([1, 3, 5, 7, 9])

In [9]:
ds.shape

(5,)

In [10]:
ds.dtype

dtype('int32')

In [11]:
ds.itemsize

4

In [12]:
x = ds.data
list(x)

[1, 3, 5, 7, 9]

In [13]:
ds.size * ds.itemsize

20

In [14]:
%%capture timeit_results
%timeit numlist = np.arange(1, 1000)

In [15]:
print(timeit_results)

The slowest run took 7.34 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 4.96 us per loop



In [16]:
np.array([[1,2],[3,4],[5,6]])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [17]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [18]:
np.zeros((3,4,5), dtype=np.int64)

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [19]:
np.linspace(1,5)

array([ 1.        ,  1.08163265,  1.16326531,  1.24489796,  1.32653061,
        1.40816327,  1.48979592,  1.57142857,  1.65306122,  1.73469388,
        1.81632653,  1.89795918,  1.97959184,  2.06122449,  2.14285714,
        2.2244898 ,  2.30612245,  2.3877551 ,  2.46938776,  2.55102041,
        2.63265306,  2.71428571,  2.79591837,  2.87755102,  2.95918367,
        3.04081633,  3.12244898,  3.20408163,  3.28571429,  3.36734694,
        3.44897959,  3.53061224,  3.6122449 ,  3.69387755,  3.7755102 ,
        3.85714286,  3.93877551,  4.02040816,  4.10204082,  4.18367347,
        4.26530612,  4.34693878,  4.42857143,  4.51020408,  4.59183673,
        4.67346939,  4.75510204,  4.83673469,  4.91836735,  5.        ])

In [20]:
np.linspace(0, 2, num=4)

array([ 0.        ,  0.66666667,  1.33333333,  2.        ])

In [21]:
np.random.random((2, 3))

array([[ 0.82796394,  0.31375809,  0.90766805],
       [ 0.9513308 ,  0.53531103,  0.52457722]])

In [22]:
np.random.random_sample((2, 3))

array([[ 0.22081407,  0.94116966,  0.63793437],
       [ 0.87607752,  0.61617631,  0.17520444]])

In [23]:
data_set = np.random.random((2, 3))
data_set

array([[ 0.58044745,  0.77746268,  0.83318418],
       [ 0.16484887,  0.92925142,  0.73154878]])

In [24]:
np.max(data_set)

0.92925141887358853

In [25]:
np.max(data_set,axis=0)

array([ 0.58044745,  0.92925142,  0.83318418])

In [26]:
np.min(data_set)

0.16484887152059824

In [27]:
np.mean(data_set)

0.66945723142253089

In [28]:
np.median(data_set)

0.75450573346265393

In [29]:
np.std(data_set)

0.24912259665731418

In [30]:
np.sum(data_set)

4.0167433885351853

 Reshape

In [31]:
data_set

array([[ 0.58044745,  0.77746268,  0.83318418],
       [ 0.16484887,  0.92925142,  0.73154878]])

In [32]:
np.reshape(data_set,(3,2))

array([[ 0.58044745,  0.77746268],
       [ 0.83318418,  0.16484887],
       [ 0.92925142,  0.73154878]])

In [33]:
np.reshape(data_set,(6,1))

array([[ 0.58044745],
       [ 0.77746268],
       [ 0.83318418],
       [ 0.16484887],
       [ 0.92925142],
       [ 0.73154878]])

In [34]:
np.reshape(data_set,(2,3))

array([[ 0.58044745,  0.77746268,  0.83318418],
       [ 0.16484887,  0.92925142,  0.73154878]])

In [35]:
np.ravel(data_set)

array([ 0.58044745,  0.77746268,  0.83318418,  0.16484887,  0.92925142,
        0.73154878])