In [1]:
import numpy as np

In [19]:
if True:
    array = np.array([1, 4, 5, 8], float)
    print "the array is" , array
    print "in index 0 we have: ",array[0]
    print "the array length is", len(array)
    print "the type of data is: ", array.dtype
    print ""
    array = np.array([[1, 2, 3], [4, 5, 6]], float)  # a 2D array/Matrix
    print "the array is", array
    print "in index 0 we have: ", array[0]
    print "in index 1 we have: ", array[1]
    print "in index 0,2 we have: ", array[0][2]
    print "the type of data is: ", array.dtype

the array is [ 1.  4.  5.  8.]
in index 0 we have:  1.0
the array length is 4
the type of data is:  float64

the array is [[ 1.  2.  3.]
 [ 4.  5.  6.]]
in index 0 we have:  [ 1.  2.  3.]
in index 1 we have:  [ 4.  5.  6.]
in index 0,2 we have:  3.0
the type of data is:  float64


In [29]:
#You can index, slice, and manipulate a Numpy array much like you would with a Python list.
if True:
    array = np.array([1, 4, 5, 8], float)
    print "the array is: ", array
    print ""
    print "the second element is: "
    print array[1]
    print ""
    print "this is a slice of first 2 elements:"
    print array[:2]
    print "this is a slice of from the second element: "
    print array[1: 4]
    print "check the upper index is excluse"
    print ""
    print "we insert an element like this: array[1] = 5.0: "
    array[1] = 5.0
    print array[1]

the array is:  [ 1.  4.  5.  8.]

the second element is: 
4.0

this is a slice of first 2 elements:
[ 1.  4.]
this is a slice of from the second element: 
[ 4.  5.  8.]
check the upper index is excluse

we insert an element like this: array[1] = 5.0: 
5.0


In [36]:
#Here are some arithmetic operations that you can do with Numpy arrays
if True:
    array_1 = np.array([1, 2, 3], float)
    array_2 = np.array([5, 2, 6], float)
    print "first array: ", array_1
    print "second array: ", array_2
    print "we sum both arrays: ", array_1 + array_2
    print "we substract the first array to second arrays: ", array_1 - array_2
    print "we multiply both arrays: ", array_1 * array_2

first array:  [ 1.  2.  3.]
second array:  [ 5.  2.  6.]
we sum both arrays:  [ 6.  4.  9.]
we substract the first array to second arrays:  [-4.  0. -3.]
we multiply both arrays:  [  5.   4.  18.]


In [37]:
#Matrix arithmetics in action
if True:
    array_1 = np.array([[1, 2], [3, 4]], float)
    array_2 = np.array([[5, 6], [7, 8]], float)
    print array_1 + array_2
    print ""
    print array_1 - array_2
    print ""
    print array_1 * array_2

[[  6.   8.]
 [ 10.  12.]]

[[-4. -4.]
 [-4. -4.]]

[[  5.  12.]
 [ 21.  32.]]


In [38]:
if True:
    array_1 = np.array([1, 2, 3], float)
    array_2 = np.array([[6], [7], [8]], float)
    print np.mean(array_1)
    print np.mean(array_2)
    print ""
    print np.dot(array_1, array_2)

2.0
7.0

[ 44.]
